version: '3.1'

services:
  web:
    image: nginx:alpine
    container_name: carmen_http
    ports:
      - "8480:80"
      - "8443:443"
    networks:
      - app-network
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/ssl
      - ..:/usr/share/nginx/html
#    command: [nginx-debug, '-g', 'daemon off;']
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - php
    links:
      - php
  php:
    build: php/
    container_name: carmen_php
    ports:
      - "9000:9000"
    networks:
      - app-network
    restart: always
    volumes:
      - ..:/var/www/html
  mariadb:
    image: mariadb:latest
    container_name: carmen_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'dbt'
      MYSQL_DATABASE: 'db'
    volumes:
      - ../var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
